package com.woniu.mapper;

import com.woniu.pojo.Permission;
import com.woniu.pojo.PermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac..permission
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    long countByExample(PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac..permission
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    int deleteByExample(PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac..permission
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac..permission
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    int insert(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac..permission
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    int insertSelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac..permission
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    List<Permission> selectByExample(PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac..permission
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    Permission selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac..permission
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    int updateByExampleSelective(@Param("record") Permission record, @Param("example") PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac..permission
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    int updateByExample(@Param("record") Permission record, @Param("example") PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac..permission
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    int updateByPrimaryKeySelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac..permission
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    int updateByPrimaryKey(Permission record);
}