package com.woniu.pojo;

public class Permission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac..permission.pid
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac..permission.pname
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac..permission.parent
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    private Integer parent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac..permission.url
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac..permission.pid
     *
     * @return the value of rbac..permission.pid
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac..permission.pid
     *
     * @param pid the value for rbac..permission.pid
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac..permission.pname
     *
     * @return the value of rbac..permission.pname
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac..permission.pname
     *
     * @param pname the value for rbac..permission.pname
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public void setPname(String pname) {
        this.pname = pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac..permission.parent
     *
     * @return the value of rbac..permission.parent
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac..permission.parent
     *
     * @param parent the value for rbac..permission.parent
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac..permission.url
     *
     * @return the value of rbac..permission.url
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac..permission.url
     *
     * @param url the value for rbac..permission.url
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }
}