package com.woniu.pojo;

public class RolePermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac..role_permission.rpid
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    private Integer rpid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac..role_permission.rid
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac..role_permission.pid
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac..role_permission.rpid
     *
     * @return the value of rbac..role_permission.rpid
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public Integer getRpid() {
        return rpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac..role_permission.rpid
     *
     * @param rpid the value for rbac..role_permission.rpid
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public void setRpid(Integer rpid) {
        this.rpid = rpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac..role_permission.rid
     *
     * @return the value of rbac..role_permission.rid
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac..role_permission.rid
     *
     * @param rid the value for rbac..role_permission.rid
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac..role_permission.pid
     *
     * @return the value of rbac..role_permission.pid
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac..role_permission.pid
     *
     * @param pid the value for rbac..role_permission.pid
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }
}