package com.woniu.pojo;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac..role.rid
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac..role.rname
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    private String rname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac..role.rid
     *
     * @return the value of rbac..role.rid
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac..role.rid
     *
     * @param rid the value for rbac..role.rid
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac..role.rname
     *
     * @return the value of rbac..role.rname
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public String getRname() {
        return rname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac..role.rname
     *
     * @param rname the value for rbac..role.rname
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public void setRname(String rname) {
        this.rname = rname;
    }
}