package com.woniu.pojo;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac..user.uid
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac..user.uname
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac..user.upwd
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    private String upwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac..user.uaccount
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    private String uaccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac..user.uemail
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    private String uemail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac..user.uid
     *
     * @return the value of rbac..user.uid
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac..user.uid
     *
     * @param uid the value for rbac..user.uid
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac..user.uname
     *
     * @return the value of rbac..user.uname
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac..user.uname
     *
     * @param uname the value for rbac..user.uname
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public void setUname(String uname) {
        this.uname = uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac..user.upwd
     *
     * @return the value of rbac..user.upwd
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public String getUpwd() {
        return upwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac..user.upwd
     *
     * @param upwd the value for rbac..user.upwd
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public void setUpwd(String upwd) {
        this.upwd = upwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac..user.uaccount
     *
     * @return the value of rbac..user.uaccount
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public String getUaccount() {
        return uaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac..user.uaccount
     *
     * @param uaccount the value for rbac..user.uaccount
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public void setUaccount(String uaccount) {
        this.uaccount = uaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac..user.uemail
     *
     * @return the value of rbac..user.uemail
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public String getUemail() {
        return uemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac..user.uemail
     *
     * @param uemail the value for rbac..user.uemail
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public void setUemail(String uemail) {
        this.uemail = uemail;
    }

	@Override
	public String toString() {
		return "User [uid=" + uid + ", uname=" + uname + ", upwd=" + upwd + ", uaccount=" + uaccount + ", uemail="
				+ uemail + "]";
	}
    
}