package com.woniu.pojo;

public class UserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac..user_role.urid
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    private Integer urid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac..user_role.uid
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac..user_role.rid
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    private Integer rid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac..user_role.urid
     *
     * @return the value of rbac..user_role.urid
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public Integer getUrid() {
        return urid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac..user_role.urid
     *
     * @param urid the value for rbac..user_role.urid
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public void setUrid(Integer urid) {
        this.urid = urid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac..user_role.uid
     *
     * @return the value of rbac..user_role.uid
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac..user_role.uid
     *
     * @param uid the value for rbac..user_role.uid
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac..user_role.rid
     *
     * @return the value of rbac..user_role.rid
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac..user_role.rid
     *
     * @param rid the value for rbac..user_role.rid
     *
     * @mbg.generated Mon Jun 08 17:52:10 CST 2020
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }
}